### ISSUE TITLE
StringIndexOutOfBoundsException: begin 0, end -1, length 0

### ISSUE THREAD

**Issue by Aquazus** [Aquazus/D1Proxy#6]
```
14:48:31 INFO f.a.d.n.ProxyClient - [77.XX.XX.XX] auth tunnel opened!
Exception in thread "Thread-1" java.lang.StringIndexOutOfBoundsException: begin 0, end -1, length 0
	at java.base/java.lang.String.checkBoundsBeginEnd(String.java:3319)
	at java.base/java.lang.String.substring(String.java:1874)
	at fr.aquazus.d1proxy.network.ProxyClient.lambda$handleClient$4(ProxyClient.java:87)
	at simplenet.Client.lambda$readByteAlways$3(Client.java:489)
	at simplenet.Client$2.accept(Client.java:442)
	at simplenet.Client$2.accept(Client.java:439)
	at simplenet.Client.read(Client.java:418)
	at simplenet.Client$2.accept(Client.java:443)
	at simplenet.Client$2.accept(Client.java:439)
	at simplenet.Client.read(Client.java:418)
	at simplenet.Client$2.accept(Client.java:443)
	at simplenet.Client$2.accept(Client.java:439)
	at simplenet.Client$Listener.completed(Client.java:95)
	at simplenet.Client$Listener.completed(Client.java:45)
	at java.base/sun.nio.ch.Invoker.invokeUnchecked(Invoker.java:127)
	at java.base/sun.nio.ch.Invoker.invokeDirect(Invoker.java:158)
	at java.base/sun.nio.ch.UnixAsynchronousSocketChannelImpl.implRead(UnixAsynchronousSocketChannelImpl.java:560)
	at java.base/sun.nio.ch.AsynchronousSocketChannelImpl.read(AsynchronousSocketChannelImpl.java:277)
	at java.base/sun.nio.ch.AsynchronousSocketChannelImpl.read(AsynchronousSocketChannelImpl.java:298)
	at java.base/java.nio.channels.AsynchronousSocketChannel.read(AsynchronousSocketChannel.java:425)
	at simplenet.Server$2.completed(Server.java:103)
	at simplenet.Server$2.completed(Server.java:97)
	at java.base/sun.nio.ch.Invoker.invokeUnchecked(Invoker.java:127)
	at java.base/sun.nio.ch.Invoker$2.run(Invoker.java:219)
	at java.base/sun.nio.ch.AsynchronousChannelGroupImpl$1.run(AsynchronousChannelGroupImpl.java:112)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by Aquazus** [comment]
Besoin d'un log d'erreur à jour avec la 1.10.2

**Comment by Aquazus** [comment]
```
17:29:43 INFO f.a.d.n.ProxyClient - [185.XXX.XXX.XXX] auth tunnel opened!
Exception in thread "Thread-81" java.lang.StringIndexOutOfBoundsException: begin 0, end -1, length 0
        at java.base/java.lang.String.checkBoundsBeginEnd(String.java:3319)
        at java.base/java.lang.String.substring(String.java:1874)
        at fr.aquazus.d1proxy.network.ProxyClient.lambda$handleClient$4(ProxyClient.java:88)
        at simplenet.Client.lambda$readByteAlways$3(Client.java:489)
        at simplenet.Client$2.accept(Client.java:442)
        at simplenet.Client$2.accept(Client.java:439)
        at simplenet.Client.read(Client.java:418)
        at simplenet.Client$2.accept(Client.java:443)
        at simplenet.Client$2.accept(Client.java:439)
        at simplenet.Client.read(Client.java:418)
        at simplenet.Client$2.accept(Client.java:443)
        at simplenet.Client$2.accept(Client.java:439)
        at simplenet.Client$Listener.completed(Client.java:95)
        at simplenet.Client$Listener.completed(Client.java:45)
        at java.base/sun.nio.ch.Invoker.invokeUnchecked(Invoker.java:127)
        at java.base/sun.nio.ch.Invoker.invokeDirect(Invoker.java:158)
        at java.base/sun.nio.ch.UnixAsynchronousSocketChannelImpl.implRead(UnixAsynchronousSocketChannelImpl.java:560)
        at java.base/sun.nio.ch.AsynchronousSocketChannelImpl.read(AsynchronousSocketChannelImpl.java:277)
        at java.base/sun.nio.ch.AsynchronousSocketChannelImpl.read(AsynchronousSocketChannelImpl.java:298)
        at java.base/java.nio.channels.AsynchronousSocketChannel.read(AsynchronousSocketChannel.java:425)
        at simplenet.Server$2.completed(Server.java:103)
        at simplenet.Server$2.completed(Server.java:97)
        at java.base/sun.nio.ch.Invoker.invokeUnchecked(Invoker.java:127)
        at java.base/sun.nio.ch.Invoker$2.run(Invoker.java:219)
        at java.base/sun.nio.ch.AsynchronousChannelGroupImpl$1.run(AsynchronousChannelGroupImpl.java:112)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)
```
