### ISSUE TITLE
java.nio.channels.ShutdownChannelGroupException

### ISSUE THREAD

**Issue by farooch** [Aquazus/D1Proxy#7]
```
Exception in thread "Thread-10" java.nio.channels.ShutdownChannelGroupException
	at java.base/sun.nio.ch.Invoker.invokeIndirectly(Invoker.java:223)
	at java.base/sun.nio.ch.Invoker.invoke(Invoker.java:189)
	at java.base/sun.nio.ch.Invoker.invoke(Invoker.java:298)
	at java.base/sun.nio.ch.WindowsAsynchronousSocketChannelImpl$ReadTask.failed(WindowsAsynchronousSocketChannelImpl.java:602)
	at java.base/sun.nio.ch.Iocp$EventHandlerTask.run(Iocp.java:389)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by Aquazus** [comment]
Related to a previous issue with the .autojoin
